name: Akshat Mahajan
title: Akshat Mahajan
description: Infrastructure Engineer
logo: https://avatars2.githubusercontent.com/u/6730980
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
