[project]
name = "site"
version = "0.1.0"
description = "Akshat Mahajan's personal website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["marimo>=0.14.12", "matplotlib>=3.10.3", "numpy>=2.3.1"]
