on:
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install marimo
          marimo export html site.py -o unprocessed.html --force --no-include-code
      - name: Post-process output
        run: |
          mkdir output
          mv resume.pdf output/resume.pdf
          awk '{
            gsub(/<meta name="description" content="a marimo app" \/>/, "<meta name=\"description\" content=\"Akshat Mahajan | Distributed Systems Engineer | Personal website\" />")
          } 1' unprocessed.html > output/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4